<?php
return [
  [
    'title' => '功能',
    'icon' => 'aicon ai-shezhi',
    'module' => 'fun',
    'url' => 'fun',
    'param' => '',
    'target' => '_self',
    'debug' => 0,
    'system' => 0,
    'nav' => 1,
    'sort' => 100,
    'childs' => [
      [
        'title' => '文章管理',
        'icon' => 'aicon ai-shouye',
        'module' => 'fun',
        'url' => 'fun/article',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '文章类别',
            'icon' => 'aicon ai-caidan',
            'module' => 'fun',
            'url' => 'fun/articleCate/articleCate',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '文章列表',
            'icon' => 'aicon ai-caidan',
            'module' => 'fun',
            'url' => 'fun/article/article',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '删除文章',
            'icon' => 'aicon ai-caidan',
            'module' => 'fun',
            'url' => 'fun/article/delArticle',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
        ],
      ],
      [
        'title' => '个人信息卡',
        'icon' => 'aicon ai-shouye',
        'module' => 'fun',
        'url' => 'fun/info',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '个人信息卡',
            'icon' => 'aicon ai-caidan',
            'module' => 'fun',
            'url' => 'fun/info/info',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
        ],
      ],
      [
        'title' => '配置',
        'icon' => 'aicon ai-shouye',
        'module' => 'fun',
        'url' => 'fun/config',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '底部配置',
            'icon' => 'aicon ai-caidan',
            'module' => 'fun',
            'url' => 'fun/footer/footer',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '头部配置',
            'icon' => 'aicon ai-caidan',
            'module' => 'fun',
            'url' => 'fun/header/header',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
        ],
      ],
      [
        'title' => '关于我',
        'icon' => 'aicon ai-caidan',
        'module' => 'fun',
        'url' => 'fun/about',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '关于我文章',
            'icon' => 'aicon ai-caidan',
            'module' => 'fun',
            'url' => 'fun/about/about',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
        ],
      ],
    ],
  ],
];
