<?php
return [
  [
    'title' => '接口',
    'icon' => 'fa fa-plug',
    'module' => 'api',
    'url' => 'api',
    'param' => '',
    'target' => '_self',
    'debug' => 0,
    'system' => 0,
    'nav' => 1,
    'sort' => 100,
    'childs' => [
      [
        'title' => '应用管理',
        'icon' => 'fa fa-adn',
        'module' => 'api',
        'url' => 'api/app',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '应用分组',
            'icon' => '',
            'module' => 'api',
            'url' => 'api/appGroup/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '新增',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/appGroup/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/appGroup/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '状态',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/appGroup/status',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/appGroup/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '应用列表',
            'icon' => '',
            'module' => 'api',
            'url' => 'api/app/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '新增',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/app/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/app/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '状态',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/app/status',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/app/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '刷新AppSecret',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/app/refreshAppSecret',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '接口管理',
        'icon' => 'fa fa-sitemap',
        'module' => 'api',
        'url' => 'app/api',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '接口分组',
            'icon' => '',
            'module' => 'api',
            'url' => 'api/apiGroup/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '新增',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/apiGroup/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/apiGroup/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '状态',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/apiGroup/status',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/apiGroup/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '接口列表',
            'icon' => '',
            'module' => 'api',
            'url' => 'api/api/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '新增',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/api/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/api/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '状态',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/api/status',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/api/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '刷新路由',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/api/refreshRoute',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '接口参数',
            'icon' => '',
            'module' => 'api',
            'url' => 'api/param/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '新增',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/param/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/param/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '状态',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/param/status',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/param/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '错误码维护',
            'icon' => '',
            'module' => 'api',
            'url' => 'api/errorCode/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '新增',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/errorCode/add',
                'param' => 'hisi_model=apiErrorCode',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/errorCode/edit',
                'param' => 'hisi_model=apiErrorCode',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '排序',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/errorCode/sort',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '状态设置',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/errorCode/status',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/errorCode/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '开发文档',
        'icon' => 'fa fa-file-word-o',
        'module' => 'api',
        'url' => 'api/doc',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '文档分类',
            'icon' => '',
            'module' => 'api',
            'url' => 'api/docCategory/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '新增',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/DocCategory/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/DocCategory/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/DocCategory/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '状态',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/DocCategory/status',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '排序',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/DocCategory/sort',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '文档列表',
            'icon' => '',
            'module' => 'api',
            'url' => 'api/doc/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '新增',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/Doc/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/Doc/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/Doc/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '状态',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/Doc/status',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '排序',
                'icon' => '',
                'module' => 'api',
                'url' => 'api/Doc/sort',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
        ],
      ],
    ],
  ],
];
